"""AtomMem public configuration.

All service credentials are read from environment variables. For local runs,
copy `.env.example` to `.env` and fill in your own values, or export the same
variables in the shell before running the pipeline.
"""

from __future__ import annotations

import os


def _get_bool(name: str, default: bool) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "y", "on"}


def _get_int(name: str, default: int) -> int:
    value = os.getenv(name)
    if value is None:
        return default
    try:
        return int(value)
    except ValueError:
        return default


def _get_float(name: str, default: float) -> float:
    value = os.getenv(name)
    if value is None:
        return default
    try:
        return float(value)
    except ValueError:
        return default


# ==================== LLM / Embedding Backends ====================
API_KEY = os.getenv("ATOMMEM_API_KEY") or os.getenv("OPENAI_API_KEY", "")
API_BASE = os.getenv("ATOMMEM_API_BASE") or os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1")
LLM_MODEL = os.getenv("ATOMMEM_LLM_MODEL", "gpt-4o-mini")
LLM_TEMPERATURE = _get_float("ATOMMEM_LLM_TEMPERATURE", 0.3)
LLM_MAX_TOKENS = _get_int("ATOMMEM_LLM_MAX_TOKENS", 2000)
LLM_REQUEST_TIMEOUT = _get_int("ATOMMEM_LLM_REQUEST_TIMEOUT", 60)
LLM_BYPASS_PROXY = _get_bool("ATOMMEM_LLM_BYPASS_PROXY", False)

FACT_EXECUTOR_API_KEY = os.getenv("ATOMMEM_FACT_EXECUTOR_API_KEY", API_KEY)
FACT_EXECUTOR_API_BASE = os.getenv("ATOMMEM_FACT_EXECUTOR_API_BASE", API_BASE)
FACT_EXECUTOR_MODEL = os.getenv("ATOMMEM_FACT_EXECUTOR_MODEL", LLM_MODEL)

EMBEDDING_MODEL = os.getenv("ATOMMEM_EMBEDDING_MODEL", "all-MiniLM-L6-v2")
EMBEDDING_DIMENSION = _get_int("ATOMMEM_EMBEDDING_DIMENSION", 384)
DRY_RUN_EMBEDDING = _get_bool("ATOMMEM_DRY_RUN_EMBEDDING", False)


# ==================== Memory Construction ====================
CONTEXT_WINDOW_K = _get_int("ATOMMEM_CONTEXT_WINDOW_K", 1)
DUPLICATE_THRESHOLD = _get_float("ATOMMEM_DUPLICATE_THRESHOLD", 0.95)

SIMILAR_FACTS_TOP_K = _get_int("ATOMMEM_SIMILAR_FACTS_TOP_K", 10)

PROFILE_BATCH_TRIGGER = _get_int("ATOMMEM_PROFILE_BATCH_TRIGGER", 10)
PROFILE_DUPLICATE_THRESHOLD = _get_float("ATOMMEM_PROFILE_DUPLICATE_THRESHOLD", 0.95)
PROFILE_TEMPORAL_TOP_K = _get_int("ATOMMEM_PROFILE_TEMPORAL_TOP_K", 8)
PROFILE_TEMPORAL_MIN_LLM_SCORE = _get_float("ATOMMEM_PROFILE_TEMPORAL_MIN_LLM_SCORE", 0.55)


# ==================== Base Retrieval ====================
MAIN_RECALL_TOP_K = _get_int("ATOMMEM_MAIN_RECALL_TOP_K", 5)
EVENT_RECALL_TOP_K = _get_int("ATOMMEM_EVENT_RECALL_TOP_K", 5)
COMPENSATION_FACT_TOP_K = _get_int("ATOMMEM_COMPENSATION_FACT_TOP_K", 5)
FINAL_RETRIEVAL_TOP_K = _get_int("ATOMMEM_FINAL_RETRIEVAL_TOP_K", 10)
PROFILE_RECALL_TOP_K = _get_int("ATOMMEM_PROFILE_RECALL_TOP_K", 5)

EMBEDDING_WEIGHT_ALPHA = _get_float("ATOMMEM_EMBEDDING_WEIGHT_ALPHA", 0.7)
KEYWORD_WEIGHT_BETA = _get_float("ATOMMEM_KEYWORD_WEIGHT_BETA", 0.3)
COMPENSATION_EVENT_WEIGHT = _get_float("ATOMMEM_COMPENSATION_EVENT_WEIGHT", 0.7)
COMPENSATION_FACT_WEIGHT = _get_float("ATOMMEM_COMPENSATION_FACT_WEIGHT", 0.3)


# ==================== Entity/Event/Turn Graph Retrieval ====================
GRAPH_RHO_KEYWORD = _get_float("ATOMMEM_GRAPH_RHO_KEYWORD", 0.45)
GRAPH_RHO_EVENT = _get_float("ATOMMEM_GRAPH_RHO_EVENT", 0.40)
GRAPH_RHO_TURN = _get_float("ATOMMEM_GRAPH_RHO_TURN", 0.15)
GRAPH_RESTART_PROB = _get_float("ATOMMEM_GRAPH_RESTART_PROB", 0.34)
GRAPH_MAX_ITER = _get_int("ATOMMEM_GRAPH_MAX_ITER", 20)
GRAPH_TOL = _get_float("ATOMMEM_GRAPH_TOL", 1e-6)

GRAPH_EVENT_SIZE_ALPHA = _get_float("ATOMMEM_GRAPH_EVENT_SIZE_ALPHA", 1.25)
GRAPH_MAX_EVENT_SIZE = os.getenv("ATOMMEM_GRAPH_MAX_EVENT_SIZE", "60")
GRAPH_MAX_EVENT_SIZE = None if GRAPH_MAX_EVENT_SIZE.lower() in {"none", "null", ""} else int(GRAPH_MAX_EVENT_SIZE)
GRAPH_MAX_EVENT_NEIGHBORS_PER_FACT = _get_int("ATOMMEM_GRAPH_MAX_EVENT_NEIGHBORS_PER_FACT", 10)

GRAPH_TURN_WINDOW = _get_int("ATOMMEM_GRAPH_TURN_WINDOW", 2)
GRAPH_TAU_TURN = _get_float("ATOMMEM_GRAPH_TAU_TURN", 2.0)
GRAPH_MAX_TURN_NEIGHBORS_PER_FACT = _get_int("ATOMMEM_GRAPH_MAX_TURN_NEIGHBORS_PER_FACT", 6)

GRAPH_MAX_SEED_FACTS = _get_int("ATOMMEM_GRAPH_MAX_SEED_FACTS", 10)
GRAPH_SEED_SCORE_POWER = _get_float("ATOMMEM_GRAPH_SEED_SCORE_POWER", 5.0)
GRAPH_MAX_NEIGHBORS_PER_FACT = _get_int("ATOMMEM_GRAPH_MAX_NEIGHBORS_PER_FACT", 30)
GRAPH_MAX_LOCAL_NODES = _get_int("ATOMMEM_GRAPH_MAX_LOCAL_NODES", 180)
GRAPH_MAX_HOPS = _get_int("ATOMMEM_GRAPH_MAX_HOPS", 2)
GRAPH_QUERY_KEYWORD_BOOST = _get_float("ATOMMEM_GRAPH_QUERY_KEYWORD_BOOST", 2.5)
GRAPH_QUERY_PENALTY_FLOOR = _get_float("ATOMMEM_GRAPH_QUERY_PENALTY_FLOOR", 0.45)
GRAPH_QUERY_PENALTY_TAU = _get_float("ATOMMEM_GRAPH_QUERY_PENALTY_TAU", 0.05)
GRAPH_QUERY_PENALTY_GAMMA = _get_float("ATOMMEM_GRAPH_QUERY_PENALTY_GAMMA", 0.7)
GRAPH_NON_QUERY_PENALTY_TAU = _get_float("ATOMMEM_GRAPH_NON_QUERY_PENALTY_TAU", 0.10)
GRAPH_NON_QUERY_PENALTY_GAMMA = _get_float("ATOMMEM_GRAPH_NON_QUERY_PENALTY_GAMMA", 1.0)
GRAPH_FINAL_TOP_K = _get_int("ATOMMEM_GRAPH_FINAL_TOP_K", 10)


# Compatibility names used by legacy core modules.
KEYWORD_GRAPH_RECALL_TOP_K = GRAPH_FINAL_TOP_K
KEYWORD_GRAPH_RESTART_PROB = GRAPH_RESTART_PROB
KEYWORD_GRAPH_MAX_ITER = GRAPH_MAX_ITER
KEYWORD_GRAPH_TOL = GRAPH_TOL
KEYWORD_GRAPH_QUERY_KEYWORD_BOOST = GRAPH_QUERY_KEYWORD_BOOST
KEYWORD_GRAPH_QUERY_PENALTY_FLOOR = GRAPH_QUERY_PENALTY_FLOOR
KEYWORD_GRAPH_QUERY_PENALTY_TAU = GRAPH_QUERY_PENALTY_TAU
KEYWORD_GRAPH_QUERY_PENALTY_GAMMA = GRAPH_QUERY_PENALTY_GAMMA
KEYWORD_GRAPH_NON_QUERY_PENALTY_TAU = GRAPH_NON_QUERY_PENALTY_TAU
KEYWORD_GRAPH_NON_QUERY_PENALTY_GAMMA = GRAPH_NON_QUERY_PENALTY_GAMMA
KEYWORD_GRAPH_NON_QUERY_SKIP_DF_RATIO = None
KEYWORD_GRAPH_MAX_SEED_FACTS = GRAPH_MAX_SEED_FACTS
KEYWORD_GRAPH_QUERY_KEYWORD_HIT_TOP_K = 80
KEYWORD_GRAPH_MAX_NEIGHBORS_PER_FACT = GRAPH_MAX_NEIGHBORS_PER_FACT
KEYWORD_GRAPH_MAX_LOCAL_NODES = GRAPH_MAX_LOCAL_NODES
KEYWORD_GRAPH_MAX_HOPS = GRAPH_MAX_HOPS
KEYWORD_GRAPH_EDGE_EPSILON = 1e-8
USE_SEMANTIC_KEYWORD_MATCHING = False
SEMANTIC_KEYWORD_THRESHOLD = 0.9


# ==================== Paths ====================
CONVERSATION_DIR = os.getenv("ATOMMEM_CONVERSATION_DIR", "data/conversations")
QA_DIR = os.getenv("ATOMMEM_QA_DIR", "data/questions")
FACTS_DIR = os.getenv("ATOMMEM_FACTS_DIR", "runs/default_memory")
PROMPTS_DIR = os.getenv("ATOMMEM_PROMPTS_DIR", "prompts")
REPORTS_DIR = os.getenv("ATOMMEM_REPORTS_DIR", "reports")

TIME_FORMAT = "%Y-%m-%d"
LOG_LEVEL = os.getenv("ATOMMEM_LOG_LEVEL", "INFO")
ENABLE_DEBUG = _get_bool("ATOMMEM_ENABLE_DEBUG", False)
